### ISSUE TITLE
Remove legacy peer dependencies

### ISSUE THREAD

**Issue by coolsoftwaretyler** [andykog/mobx-devtools#118]
In https://github.com/mobxjs/mobx-devtools/pull/116, we bumped from Node v10 to v20, but that change requires us to use [`--legacy-peer-deps`](https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh).

We should fix our peer dependencies to work correctly without the legacy flag.

**Comment by coolsoftwaretyler** [comment]
I had someone email me about taking this on. We made a plan. I don't know their GitHub handle so I can't assign this to them yet, but we do have a volunteer to get started here (as far as I know).

I'll keep an eye on it and remind them if there isn't progress over the weekend.

**Comment by coolsoftwaretyler** [comment]
I haven't heard from them for a while, so I followed up. If I don't hear back by tomorrow I'll just take this one myself next week.

**Comment by grvv** [comment]
@coolsoftwaretyler, Hey sorry for delaying things a bit, due to issues with my personal laptop. You can assign me the issue now 🖖

**Comment by coolsoftwaretyler** [comment]
Done! Let me know if you need anything

**Comment by coolsoftwaretyler** [comment]
Hi @grvv - any update on your end?

I am going to be on vacation next week, back on Friday/Saturday. If you haven't made progress by then, I'll reassign to myself and get things moving. 

Not a problem if you've been too busy to work on it, but I don't want to put this off too long and I've got a little time next weekend to work on it myself. Lots more to be done to get things up and running.

**Comment by grvv** [comment]
Hey @coolsoftwaretyler!

I didn't realize there was a bit of urgency here; I thought I could take my time and work on it gradually. I’ve cloned the repo and started diving into the code. I have a couple of light days at work starting today, so I’ll dedicate some time to it and try to make progress before your vacation. 

Thanks for the reminder! 🖖

**Comment by coolsoftwaretyler** [comment]
Thanks @grvv!

**Comment by coolsoftwaretyler** [comment]
Hi @grvv - I'm hoping to get to this sometime this week. Have you made any progress? I don't want to duplicate or supersede any work you've done.

No shame at all if you haven't gotten around to it. I just want to know so I can move forward with the work. There's plenty of stuff left to do if you want to contribute something else!

Thanks for your time so far.

**Comment by grvv** [comment]
Hey @coolsoftwaretyler,

I just added my draft PR! 🖖

Here’s what I’ve done so far: I started by installing the dependencies without using the --legacy-peer-deps flag and noticed that the Babel loader needed an update. So, I went ahead and updated the Babel loader, its presets/plugins, and migrated Webpack from v3 to v4.

Next, I’ll focus on resolving the remaining peer dependencies one at a time.

[PR Link](https://github.com/mobxjs/mobx-devtools/pull/121)

I’ve kept it as a draft for now to hear your thoughts or suggestions. I think we both should collaborate on this. I initially thought it’d be a quick fix, but it looks like it might take a bit longer since some dependencies will need code changes (e.g., switching from "react-addons-test-utils" to react-testing-library, and possibly updating the React version itself). I’ve attached a screenshot that highlights this.

<img width="603" alt="Screenshot 2024-10-15 at 1 43 20 AM" src="https://github.com/user-attachments/assets/be358040-35d1-4ea4-8956-4c8ddf469701">


Looking forward to your feedback!

**Comment by coolsoftwaretyler** [comment]
I'll take a look!

**Comment by grvv** [comment]
@coolsoftwaretyler updated PR: 

https://github.com/mobxjs/mobx-devtools/pull/122

**Comment by coolsoftwaretyler** [comment]
Excellent thank you! Done in https://github.com/mobxjs/mobx-devtools/pull/122
